### PR TITLE
feat: enable landscape mode on home page and search apps

### PR DESCRIPTION
**Pull request by toby-bro**
Adds feature #6 

Didn't do it in the settings as it needs a little refactoring to be usable

### CODE REVIEW

**Comment by toby-bro** [comment]
@jrpie Do you want me to also enable it in the settings page ?

Furthermore do you want me to add an option to opt out of this If one wants his launcher to stay in full portrait mode ?

**Comment by jrpie** [comment]
Thank you! I think an option for this would be nice. Personally I find it quite annoying when my home screen accidentally switches to landscape.

Settings definitely need refactoring. I think it would be best to do that first (#23) and then implement this feature.

**Comment by toby-bro** [comment]
Ok so I'll add a switch in the options for that.

**Comment by jrpie** [comment]
I reworked the settings page and implemented this in c89e7420

**Pull request closed without merging**
