### PR TITLE
Chore: android permissions

### PR DESCRIPTION
**Pull request by toby-bro**
Modifications :
- Since Android 11 it is not necessary to ask for `WRITE_EXTERNAL_STORAGE` and since Android 13 it is deprecated 
- Let Android studio reformat the file as he wanted
- Added a permission to the exported field of settings to prevent any app from calling the launcher's settings (the exact permission can be discussed if you think of a more appropriate one)

### CODE REVIEW

**Comment by jrpie** [comment]
Why was `WRITE_EXTERNAL_STORAGE` even needed in the first place? Is this still left over from when the app managed the wallpaper itself?

**Comment by jrpie** [comment]
I don't understand what `android:permission="android.permission.MANAGE_APP_PERMISSIONS"` is supposed to do. Is that documented anywhere?

**Comment by toby-bro** [comment]
Write external storage was necessary before android 11 to be able to save app data on the phone. But since android 11 it is not needed as apps' storage is compartmentalised.

**Comment by toby-bro** [comment]
You're right this is weird... 
I thought it was suggested as autocomplete, but maybe it's copilot who hallucinated. 
After having checked the doc I think I'll have to change the permission to a real one 😅 (or at least a documented one)
- https://developer.android.com/guide/components/activities/intro-activities
- https://developer.android.com/reference/android/Manifest.permission
- https://developer.android.com/guide/topics/manifest/activity-element
The objective was making sure no app could change the settings malevolently

**Comment by jrpie** [comment]
"Access" just means that other apps can launch an intent to start this activity. I don't see why that should be a problem.

**Comment by jrpie** [comment]
Merged this from CLI, somehow github doesn't detect it.

**Pull request closed without merging**
